from django.db import models

# Create your models here.
NOTIFICATION_TYPES = (
    ('STUDENT_REQUEST_SENT', 'STUDENT_REQUEST_SENT'),
    ('STUDENT_REQUEST_ACCEPTED', 'STUDENT_REQUEST_ACCEPTED'),
    ('STUDENT_REQUEST_REJECTED', 'STUDENT_REQUEST_REJECTED'),
    ('STUDENT_INVITED', 'STUDENT_INVITED'),
    ('STUDENT_COURSE_COMPLETED', 'STUDENT_COURSE_COMPLETED'),
    ('STUDENT_NEW_ANSWER', 'STUDENT_NEW_ANSWER'),
    ('PROFESSOR_NEW_QUESTION', 'PROFESSOR_NEW_QUESTION'),
    ('PROFESSOR_ENROLMENT_REQUEST', 'PROFESSOR_ENROLMENT_REQUEST'),
    ('ADMIN_NEW_COURSE', 'ADMIN_NEW_COURSE'),
    ('ADMIN_NEW_ENROLMENT', 'ADMIN_NEW_ENROLMENT'),
)

class Notification(models.Model):
    name = models.CharField(max_length=16)
    