# Generated by Django 4.1.5 on 2023-01-29 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_professor_alter_course_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='token',
        ),
    ]
