# Generated by Django 4.1.5 on 2023-02-17 06:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='face',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='face'),
        ),
    ]
