# Generated by Django 4.1.4 on 2023-01-02 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
        ('course', '0002_alter_course_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('STUDENT_REQUEST_SENT', 'STUDENT_REQUEST_SENT'), ('STUDENT_REQUEST_ACCEPTED', 'STUDENT_REQUEST_ACCEPTED'), ('STUDENT_REQUEST_REJECTED', 'STUDENT_REQUEST_REJECTED'), ('STUDENT_INVITED', 'STUDENT_INVITED'), ('STUDENT_COURSE_COMPLETED', 'STUDENT_COURSE_COMPLETED'), ('STUDENT_NEW_ANSWER', 'STUDENT_NEW_ANSWER'), ('PROFESSOR_NEW_QUESTION', 'PROFESSOR_NEW_QUESTION'), ('PROFESSOR_ENROLMENT_REQUEST', 'PROFESSOR_ENROLMENT_REQUEST'), ('ADMIN_NEW_COURSE', 'ADMIN_NEW_COURSE'), ('ADMIN_NEW_ENROLMENT', 'ADMIN_NEW_ENROLMENT'), ('ADMIN_PROMOTION_REQUEST', 'ADMIN_PROMOTION_REQUEST')], max_length=32)),
                ('text', models.CharField(max_length=1024)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.message')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
